@idToken = replace-with-firebase-id-token

GET http://localhost:5000/discussions/posts
###

POST http://localhost:5000/discussions/posting
Content-Type: application/json
Authorization: Bearer {{idToken}}

{
  "Author": "John Doe",
  "Date": "20250603",
  "Title": "New Discussion Topic",
  "Description": "This is a description of the new discussion topic."
}

### post a comment to a discussion post

POST http://localhost:5000/discussions/post/4JXBLNoIgwGc279xhvqR/comment
Content-Type: application/json
Authorization: Bearer {{idToken}}

{
  "author": "John Doe",
  "content": "Test comment content",
  "date": "20250603"
}
### delete a comment from a discussion post

DELETE http://localhost:5000/discussions/comment/4JXBLNoIgwGc279xhvqR/1749339986789
Authorization: Bearer {{idToken}}

### delte a discussion post

DELETE http://localhost:5000/discussions/post/ZFSc5TxDgbFBvryyxGWF
Authorization: Bearer {{idToken}}


