@idToken = replace-with-admin-or-editor-firebase-id-token

### posts one news post

POST http://localhost:5000/news/posting
Content-Type: application/json
Authorization: Bearer {{idToken}}

{
  "Author": "John Doe",
  "Date": "20250603",
  "Title": "New Discussion Topic",
  "Description": "This is a description of the new discussion topic."
}

### get all news posts

GET http://localhost:5000/news/posts
Content-Type: application/json
