@idToken = replace-with-firebase-id-token

### Review Posting API Test
POST http://localhost:5000/reviews/posting
Content-Type: application/json
Authorization: Bearer {{idToken}}

{
  "movieId": "950387",
  "Author": "John Doe",
  "content": "This movie was fantastic! A must-watch for everyone.",
  "rating": "5"
}

### delte 

DELETE http://localhost:5000/reviews/HiqffYVzvJAw6YjZbHxV
Authorization: Bearer {{idToken}}


### update

PATCH http://localhost:5000/reviews/k2dGWDfMPbGslHqLN6hs
Content-type: application/json
Authorization: Bearer {{idToken}}

{
  "content": "This movie was fantastic! A must-watch for everyone. Updated review.",
  "rating": "3"
}
